substitutions:
  _EXERCICIO_K8S_VERSION: 1.0.1
steps:
  - id: "Executando build do container"
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/webserver-go-greeting:${_EXERCICIO_K8S_VERSION}'
      - '-t'
      - 'gcr.io/$PROJECT_ID/webserver-go-greeting:latest' 
      - './3-desafio_go/'

  - id: "Rodando testes ..."
    name: 'gcr.io/cloud-builders/go'
    args: ['test', 'server']
    env: ['PROJECT_ROOT=server']
    dir: './3-desafio_go/'

  - id: "Executando o build da aplicação."
    name: 'gcr.io/cloud-builders/go'
    args: ['build', '-o', 'greeting/webserver-go-greeting']
    env: ['PROJECT_ROOT=server']
    dir: './3-desafio_go/'

  # - id: "Instalando o GO ..."
  #   name: 'gcr.io/cloud-builders/go'
  #   args: ['install', '.']
  #   env: ['PROJECT_ROOT=server']
  #   dir: './3-desafio_go/'

images:
  - 'gcr.io/$PROJECT_ID/webserver-go-greeting:latest'
  - 'gcr.io/$PROJECT_ID/webserver-go-greeting:${_DESAFIO_CI_VERSION}'
tags: ['fullcycle-exercicio-k8s']